import raw from './graphemeIndex.json'
import type { ActivityType, CurriculumPhaseNumber } from './types'

/**
 * Lightweight per-grapheme summary for the home/picker page — generated by
 * scripts/generate-grapheme-index.mjs from the same phase JSON files that back the full
 * `data/graphemes.ts`. Deliberately excludes words/segments/sentences/etc: the picker page
 * only ever needs id/grapheme/keyword/phase/type, and importing the full curriculum data here
 * would pull ~400KB of JSON into the main bundle before the user has clicked anything.
 */
export interface GraphemeIndexEntry {
  id?: string
  grapheme: string
  keyword: string
  phase: number
  type?: 'grapheme' | 'morpheme'
}

interface GraphemeIndexJson {
  byPhase: Record<string, GraphemeIndexEntry[]>
  activityAllowlist: Record<string, ActivityType[]>
}

const data = raw as GraphemeIndexJson

export const GRAPHEME_INDEX_BY_PHASE: Record<number, GraphemeIndexEntry[]> = Object.fromEntries(
  Object.entries(data.byPhase).map(([k, v]) => [Number(k), v]),
)

/** Phase order used across the home grid (2 → 3 → 4 → 5). */
export const CURRICULUM_PHASES_ORDERED = [2, 3, 4, 5] as const satisfies readonly CurriculumPhaseNumber[]

export const ALL_GRAPHEME_INDEX: GraphemeIndexEntry[] = Object.values(GRAPHEME_INDEX_BY_PHASE).flat()

/** Lookup by curriculum id when present, else display grapheme — mirrors data/graphemes.ts's graphemeMap. */
export const GRAPHEME_INDEX_MAP = new Map(ALL_GRAPHEME_INDEX.map((e) => [e.id ?? e.grapheme, e]))

export const INDEX_ACTIVITY_ALLOWLIST: Partial<Record<number, ActivityType[]>> = Object.fromEntries(
  Object.entries(data.activityAllowlist).map(([k, v]) => [Number(k), v]),
)

export function intersectActivityAllowlistForIndexSelection(
  selection: GraphemeIndexEntry[],
): Set<ActivityType> | null {
  let allow: Set<ActivityType> | null = null
  for (const g of selection) {
    const list = INDEX_ACTIVITY_ALLOWLIST[g.phase]
    if (!list?.length) continue
    const next = new Set<ActivityType>(list)
    if (allow === null) {
      allow = next
    } else {
      const prev: Set<ActivityType> = allow
      allow = new Set([...prev].filter((t) => next.has(t)))
    }
  }
  return allow
}
